apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-1
  namespace: tomcat-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: tomcat:9.0
          ports:
            - containerPort: 8080
